config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "events#index"

  resources :events, only: [:show] do
    member do
      post :attend
      delete :unattend
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  
  has_many :bookings
  has_many :users, through: :bookings


  def is_future_event?
    start_time > Time.now
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  enum gender: {male: 'male', female: 'female', other: 'other'}

  has_many :bookings
  has_many :events, through: :bookings


  def is_attending_event?(event_id)
    bookings.where(event_id: event_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_event, only: [:show, :attend, :unattend]

  def index
    @events = Event.all.order(created_at: :desc)
  end

  def show
    @users = @event.users
  end

  def attend
    booking = @event.bookings.create(user_id: current_user.id)
    if booking
      flash[:success] = "Attending Event"
      redirect_to event_path(@event)
    else
      flash[:alert] = booking.errors.full_messages.join('<br>')
      redirect_to event_path(@event)
    end

  end

  def unattend
    booking = @event.bookings.find_by(user_id: current_user.id)
    if booking.try(:destroy)
      flash[:success] = "Unattended Event"
      redirect_to event_path(@event)
    else
      flash[:alert] = booking.errors.full_messages.join('<br>')
      redirect_to event_path(@event)
    end
  end

  private
  def find_event
    @event = Event.find_by(id: params[:id]) if params[:id]
    unless @event.present?
      flash[:alert] = "Event not found"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.erb
<h1 class="text-center">List of Events</h1>
<div class="container">
  <div class="col-xs-12">
    <div class="row">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Title</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= link_to(event.name, event_path(event)) %></td>
              <td><%= event.start_time.strftime("%d.%m.%Y %H:%M") %></td>
              <td><%= event.end_time.strftime("%d.%m.%Y %H:%M") %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div>
  <h1><%= @event.name %></h1>
</div>

<div class="row">
  Start Time: <%= @event.start_time.strftime("%d.%m.%Y %H:%M") %>
  End Time: <%= @event.end_time.strftime("%d.%m.%Y %H:%M") %>
</div>

<% if user_signed_in? && @event.is_future_event? %>
  <div class="pull-right">
    <% if current_user.is_attending_event?(@event.id)%>
      <div>
        <%= link_to("Un-attend", unattend_event_path , method: :delete, class: 'btn btn-default btn-primary' ) %>
      </div>
    <% else %>
      <div>
        <%= link_to("Attend", attend_event_path , method: :post, class: 'btn btn-default btn-primary' ) %>
      </div>
    <% end %>
  </div>
<% end %>

<div class="row">
  <h3>
    Users Attending
  </h3>
</div>
<div class="row">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Gender</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.gender %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <ul class="nav nav-pills navbar-right ">
      <li>
        <%= link_to('Home', root_path, class: "btn btn-default navbar-btn" ) %>
      </li>
      <% if user_signed_in? %>
        <li>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "btn btn-default navbar-btn") %>
        </li>
      <% else %>
        <li>
        <%= link_to('Login', new_user_session_path, class: "btn btn-default navbar-btn") %>
        </li>
        <li>
        <%= link_to('Register', new_user_registration_path, class: "btn btn-default navbar-btn") %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeecashAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>